spring:
  application:
    name: train-reservation-system
  
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    defer-datasource-initialization: true
  
  sql:
    init:
      mode: always
      data-locations: classpath:sample-data.sql

  h2:
    console:
      enabled: true

server:
  port: 8080

logging:
  level:
    fr.niji.example.trainresa: DEBUG
    org.springframework.transaction: DEBUG 